name: Release

on:
  push:
    branches: [master]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v3
        with:
          release-type: go
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          bump-minor-pre-major: true
