name: Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    name: Test
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version: stable
          cache: false

      - uses: golangci/golangci-lint-action@v3
        with:
          version: latest

      - run: go build -o test ./testdata
